-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.friends_tb
(
    pengirim_id integer,
    penerima_id integer
);

CREATE TABLE IF NOT EXISTS public.members_tb
(
    user_id integer NOT NULL,
    username integer NOT NULL,
    email character varying(255) NOT NULL,
    firstname character varying(50) NOT NULL,
    lastname character varying(50),
    phonenumber integer NOT NULL,
    password character varying(255) NOT NULL,
    email_verified character varying(255),
    image_file character varying(255),
    identity_type character varying(255),
    identity_no character varying(16),
    emergency_call character varying(13),
    address_ktp character varying(255) NOT NULL,
    domisili character varying(255),
    create_date time with time zone NOT NULL,
    update_date time with time zone NOT NULL,
    PRIMARY KEY (user_id)
);

ALTER TABLE public.friends_tb
    ADD FOREIGN KEY (pengirim_id)
    REFERENCES public.members_tb (user_id)
    NOT VALID;

END;